Feature/api auth
ADEPT-Informatique/lan.adeptinfo.ca pull request #25
Opened 2022-09-20 04:01 UTC by HandsomeRomanian

2022-09-20 04:33 UTC, DeveloperAnonymous requested changes

2022-09-20 04:33 UTC, DeveloperAnonymous commented on api-adept/.gitignore
> +service-account-file.json
newline

2022-09-20 04:33 UTC, DeveloperAnonymous commented on lan-adept/.editorconfig
> +# Editor configuration, see http://editorconfig.org
https

2022-09-20 04:33 UTC, DeveloperAnonymous commented on lan-adept/.firebaserc
> +}
newline

2022-09-20 04:33 UTC, DeveloperAnonymous commented on lan-adept/.prettierrc
> +  "singleQuote": true,
Perso je penses que double > single

2022-09-20 04:33 UTC, DeveloperAnonymous commented on lan-adept/src/app/pages/auth/logout/logout.component.ts
> +	selector: 'app-logout',
Le prettier est censé être en 2 spaces width:
  "tabWidth": 2,
  "useTabs": false,

2022-09-20 04:33 UTC, DeveloperAnonymous commented on lan-adept/src/app/pages/auth/login/login.component.ts
> +	selector: 'app-login',
Même chose que le logout

2022-09-20 04:33 UTC, DeveloperAnonymous commented on lan-adept/src/environments/environment.prod.ts
>  export const environment = {
more leak?

2022-09-20 04:33 UTC, DeveloperAnonymous commented on lan-adept/src/environments/environment.ts
>  export const environment = {
more leaks?

2022-09-20 14:43 UTC, HandsomeRomanian commented on lan-adept/src/environments/environment.ts
>  export const environment = {
c'est pas des leaks, tout ce qui est dans les environements le monde y ont access en chargeant la page. Tout ce qui est dans le client est "publique"

2022-09-20 23:12 UTC, DeveloperAnonymous commented on lan-adept/src/environments/environment.ts
>  export const environment = {
Ahhh ok

2022-09-20 23:20 UTC, DeveloperAnonymous approved these changes, later dismissed
On devrait pas push le `service-account-file.json` 

Après ça, ça va être bon pour être merge

2022-09-20 23:20 UTC, DeveloperAnonymous commented on api-adept/api-adept/Services/IUsersService.cs
> +}
New line

2022-09-20 23:20 UTC, DeveloperAnonymous commented on api-adept/api-adept/service-account-file.json
> +{
jpenses pas que c'est censé être là

2022-09-22 03:27 UTC, DeveloperAnonymous approved these changes

2022-09-22 03:29 UTC, merged